# Generated by Django 4.0.2 on 2022-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ngo_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
